### ISSUE TITLE
Can't start after update kernel

### ISSUE THREAD

**Issue by gerardo-junior** [anetczuk/ClevoKeyboardControl#2]
OS: majaro
version: latest

![image](https://user-images.githubusercontent.com/9096410/102811623-67329d80-43a4-11eb-8f4f-67afc91319e9.png)

**Comment by anetczuk** [comment]
Hello,
it seems that You have problem with tuxedo keyboard driver.
Last line says everything **No such file or directory: /sys/devices/platform/tuxedo_keyboard**

Please investigate if driver is installed/loaded or if it has different location in **/sys** subsystem.

**Comment by gerardo-junior** [comment]
is installed, it was not yet functional. but I realized that the problem is in the drive. I will close it and open it in the repo da tuxedo
