### ISSUE TITLE
Saved settings

### ISSUE THREAD

**Issue by giovannicaligaris** [anetczuk/ClevoKeyboardControl#4]
This is not a bug but a question.

Where can I can find the file that stores the save settings for the app?

**Comment by giovannicaligaris** [comment]
Nevermind, I found it.

**Comment by anetczuk** [comment]
Just for the record: `{user_home_dir}/.config/arnet/ClevoKeyboardControl.ini`. Application uses Qt (`QSettings`) for persistancy of application state.
