### ISSUE TITLE
Permissions tab

### ISSUE THREAD

**Issue by junocomp** [anetczuk/ClevoKeyboardControl#5]
Sometimes the app opens and everything looks fine but it still can't keyboard drivers. 

Is it possible to add a tab called Permissions to reload the drivers?

Otherwise I have to close and open a few times the app until it gives me the possibility to reload drivers (main window)

**Comment by anetczuk** [comment]
Hello, please send me a log file (if the file grown to big size then extract extract recent part of it) -- I'll see what is going on.
